#ifndef IDT_H
#define IDT_H

#include "types.h"

/* Interrupt numbers */
enum {
	INUM_DIVISION_BY_ZERO,
	INUM_DEBUG,
	INUM_NMI,
	INUM_BREAKPOINT,
	INUM_INTO_DETECTED_OVERFLOW,
	INUM_OUT_OF_BOUNDS,
	INUM_INVALID_OPCODE,
	INUM_NO_COPROCESSOR,
	INUM_DOUBLE_FAULT,
	INUM_COPROCESSOR_SEGMENT_OVERRUN,
	INUM_BAD_TSS,
	INUM_SEGMENT_NOT_PRESENT,
	INUM_STACK_FAULT,
	INUM_GENERAL_PROTECTION_FAULT,
	INUM_PAGE_FAULT,
	INUM_RESERVED,
	INUM_COPROCESSOR_FAULT,
	INUM_ALIGNMENT_CHECK,
	INUM_MACHINE_CHECK,

	INUM_IRQ0 = 32,
	INUM_IRQ1,
	INUM_IRQ2,
	INUM_IRQ3,
	INUM_IRQ4,
	INUM_IRQ5,
	INUM_IRQ6,
	INUM_IRQ7,
	INUM_IRQ8,
	INUM_IRQ9,
	INUM_IRQ10,
	INUM_IRQ11,
	INUM_IRQ12,
	INUM_IRQ13,
	INUM_IRQ14,
	INUM_IRQ15,

	INUM_SYSCALL = 255
};

void idt_init();
void idt_install_isr(uint8_t irq_num, void (*handler)());

#endif
