#ifndef IDT_H
#define IDT_H

#include "types.h"

/* Interrupt numbers */
enum {
	INUM_DIVISION_BY_ZERO,
	INUM_DEBUG,
	INUM_NMI,
	INUM_BREAKPOINT,
	INUM_INTO_DETECTED_OVERFLOW,
	INUM_OUT_OF_BOUNDS,
	INUM_INVALID_OPCODE,
	INUM_NO_COPROCESSOR,
	INUM_DOUBLE_FAULT,
	INUM_COPROCESSOR_SEGMENT_OVERRUN,
	INUM_BAD_TSS,
	INUM_SEGMENT_NOT_PRESENT,
	INUM_STACK_FAULT,
	INUM_GENERAL_PROTECTION_FAULT,
	INUM_PAGE_FAULT,
	INUM_RESERVED,
	INUM_COPROCESSOR_FAULT,
	INUM_ALIGNMENT_CHECK,
	INUM_MACHINE_CHECK,

	INUM_ISR0 = 32,
	INUM_ISR1,
	INUM_ISR2,
	INUM_ISR3,
	INUM_ISR4,
	INUM_ISR5,
	INUM_ISR6,
	INUM_ISR7,
	INUM_ISR8,
	INUM_ISR9,
	INUM_ISR10,
	INUM_ISR11,
	INUM_ISR12,
	INUM_ISR13,
	INUM_ISR14,
	INUM_ISR15
};

void idt_init();
void idt_install_isr(uint8_t irq_num, void (*handler)());

#endif
